# Generated by Django 4.1.4 on 2022-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_categori_product_categori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentable',
            field=models.BooleanField(default=True),
        ),
    ]
